# SPDX-FileCopyrightText: 2026 Andrey Kotlyar <guitar0.app@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Block external access to node-exporter
  community.general.ufw:
    rule: deny
    port: "9100"
    proto: tcp
    comment: "Block external access to node-exporter"
