# SPDX-FileCopyrightText: 2026 Andrey Kotlyar <guitar0.app@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Deploy frontend nginx vhost config
  ansible.builtin.template:
    src: nginx-site.j2
    dest: "/etc/nginx/sites-available/{{ frontend_app_name }}"
    mode: "0644"
  notify: Reload nginx

- name: Enable frontend nginx site
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ frontend_app_name }}"
    dest: "/etc/nginx/sites-enabled/{{ frontend_app_name }}"
    state: link
  notify: Reload nginx

- name: Test nginx configuration
  ansible.builtin.command: nginx -t
  changed_when: false
