# SPDX-FileCopyrightText: 2026 Andrey Kotlyar <guitar0.app@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Create journald drop-in directory
  ansible.builtin.file:
    path: /etc/systemd/journald.conf.d
    state: directory
    mode: "0755"

- name: Limit journald disk usage
  ansible.builtin.copy:
    content: |
      [Journal]
      SystemMaxUse={{ journald_system_max_use }}
    dest: /etc/systemd/journald.conf.d/size.conf
    mode: "0644"
  notify: Restart journald
