# SPDX-FileCopyrightText: 2026 Andrey Kotlyar <guitar0.app@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Reload prometheus
  become_user: "{{ app_user }}"
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring_dir }}"
    services:
      - prometheus
    state: restarted

- name: Reload alertmanager
  become_user: "{{ app_user }}"
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring_dir }}"
    services:
      - alertmanager
    state: restarted

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
