# SPDX-FileCopyrightText: 2026 Andrey Kotlyar <guitar0.app@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
# Production environment — non-secret variables
# Secrets (passwords, tokens, keys) live in vault.yml

app_env: production

# --- Backend ---
backend_app_port: 8001
backend_db_docker_port: 5434

backend_nginx_domains:
  - server_name: api.guitar0.net
    x_frame_options: DENY
    serve_static: true
    serve_media: true
    locations:
      - path: /admin-guitar0/
        rate_limit: general_limit
        allow_only:
          - 127.0.0.1
      - path: /
        rate_limit: api_limit
  - server_name: admin.guitar0.net
    x_frame_options: SAMEORIGIN
    serve_static: true
    locations:
      - path: /admin-guitar0/
        rate_limit: general_limit
        burst: 10
        allow_only:
          - 91.203.143.0/24
      - path: /markdownx/
        rate_limit: general_limit
        burst: 10
        allow_only:
          - 91.203.143.0/24
      - path: /
        return: "301 /admin-guitar0/"

# --- Frontend ---
frontend_app_port: 3001
frontend_api_url: api.guitar0.net

frontend_nginx_domains:
  - server_name: guitar0.net
    locations:
      - path: /
        rate_limit: general_limit
